# Generated by Django 5.1.3 on 2024-11-17 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heating', '0002_temp_segment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='temp_actual',
            new_name='_temp_actual',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='temp_default',
            new_name='_temp_default',
        ),
        migrations.RenameField(
            model_name='temp_segment',
            old_name='temp_max',
            new_name='_temp_max',
        ),
        migrations.RenameField(
            model_name='temp_segment',
            old_name='temp_min',
            new_name='_temp_min',
        ),
        migrations.RenameField(
            model_name='temp_segment',
            old_name='time_end',
            new_name='_time_end',
        ),
        migrations.RenameField(
            model_name='temp_segment',
            old_name='time_start',
            new_name='_time_start',
        ),
    ]
